### ISSUE TITLE
How to fetch other user profile anonymously

### ISSUE THREAD

**Issue by nlubello** [baasbox/Android-SDK#38]
Hi,
I've tried to use the BaasUser.fetch() method but it gives this message:
{"result":"error","message":"Missing both Session Token and Authorization info","resource":"/user/****","method":"GET","request_header":{"X-BAASBOX-APPCODE":["1234567890"],"Connection":["Keep-Alive"],"Accept-Encoding":["gzip"],"User-Agent":["BaasBox AndroidSDK/0.8.4"],"Host":["www.XXXXX.com:9000"]},"API_version":"0.9.1-20150112-nightly","http_code":401}

So it's how it's possible to get the visibleByAnonymousUsers property of BaasUser??

Thanks in advance

**Comment by giastfader** [comment]
This is a server-side bug, your call has to work.
Thank you for your advice.
I open an issue on the server repo

**Comment by relgames** [comment]
Hi, is this issue fixed in 0.9.4? Seems like I still can't fetch a user profile anonymously.
