### ISSUE TITLE
GCM regression during registration

### ISSUE THREAD

**Issue by eliantor** [baasbox/Android-SDK#40]

**Comment by giastfader** [comment]
see https://groups.google.com/forum/#!msg/baasbox/2coLb_TgsaA/1ZI9eq8xXvQJ

**Comment by guiduroy** [comment]
How can we obtain the latest SKD with this bug fixed?

**Comment by guiduroy** [comment]
Up

**Comment by eliantor** [comment]
The bug is fixed on the master branch, and there are instructions on the readme on how to use it.

I'll cut a release as soon as possible.

**Comment by guiduroy** [comment]
i get this error when building : "failed to find target android-21 : /Users/Will/Downloads/Android-SDK-master"

**Comment by guiduroy** [comment]
i get this error when building : "failed to find target android-21 : /Users/Will/Downloads/Android-SDK-master"

**Comment by eliantor** [comment]
Those are the settings to build the sdk,
I suppose you need to update your sdk installation.
Make sure to have those downloaded:

compileSdkVersion 21
buildToolsVersion "21.1.2"

I'll add a comment in the readme to clarify this

**Comment by guiduroy** [comment]
alright, i'll manage to build, now i have the "library-0.9.3-SNAPSHOT.jar" file, do i simply add that to the libs file where i currently have "baasbox-android-0.9.2.jar" or replace it ?

**Comment by eliantor** [comment]
You cannot keep both libraries on the classpath, so you should replace it

**Comment by guiduroy** [comment]
in my dependencies section in the build.gradle file i use "compile fileTree(dir: 'libs', include: ['*.jar'])" to compile all the jars in the libs file which now currently only has the "library-0.9.3-SNAPSHOT.jar" file and now the whole project cannot resolve the symbol baasbox...

**Comment by eliantor** [comment]
you mean any baasbox. in the import section?

**Comment by guiduroy** [comment]
exactly

**Comment by eliantor** [comment]
Ok sorry my fault:
There is a missing dependency between tasks in the gradle build file.

before:
```
./gradlew library:coreLibJar
```
do this:

```
./gradlew library:compileReleaseJava
```

You will have a new jar that you can include in the libs folder

**Comment by guiduroy** [comment]
ok now it works with the 0.9.3 version but unfortunately the original error is replaced with another :(

Process: be.uclouvain.lfsab1509.sportfriends, PID: 21091
    java.lang.RuntimeException: java.lang.NullPointerException
            at com.baasbox.android.ExceptionHandler$1.onError(ExceptionHandler.java:33)
            at com.baasbox.android.impl.Dispatcher$Worker.run(Dispatcher.java:174)
     Caused by: java.lang.NullPointerException
            at com.baasbox.android.RequestFactory.getEndpoint(RequestFactory.java:342)
            at com.baasbox.android.BaasCloudMessagingService$RegisterMessaging.request(BaasCloudMessagingService.java:403)
            at com.baasbox.android.NetworkTask.asyncCall(NetworkTask.java:141)
            at com.baasbox.android.BaasCloudMessagingService$RegisterMessaging.asyncCall(BaasCloudMessagingService.java:376)
            at com.baasbox.android.BaasCloudMessagingService$RegisterMessaging.asyncCall(BaasCloudMessagingService.java:346)
            at com.baasbox.android.impl.Task.execute(Task.java:189)
            at com.baasbox.android.impl.Dispatcher$Worker.run(Dispatcher.java:170)

**Comment by eliantor** [comment]
Ok I'm looking at the issue

**Comment by eliantor** [comment]
Could you please share your logs, just before the error happens?

**Comment by guiduroy** [comment]
It's the same as before when I call the enable method to activate a
baasuser 's push notification system. The enable method causes the crash

**Comment by eliantor** [comment]
I know that it crashes in the same place and I apologize for the quite obscure error.
But the test with a valid sender id passes so, and the issue is unreleated. So could you please check the logs before the null pointer?

**Comment by eliantor** [comment]
I' ve updated the master branch, the npe, was due to a google cloud messaging error that was hidden from you. Now if you pull and rebuild the library, this should fix the npe, and show the real error that is happening, most probably due to a misconfiguration of the client id.

**Comment by guiduroy** [comment]
It works !! :) thank you so much !
